name: Build
run-name: Windows Build
on: [push]

jobs:
  build:
    name: Build
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Corretto JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '11'
          cache: 'maven'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots clean package -DskipTests
