name: Build
run-name: Windows Build
on: [push]

jobs:
  build:
    name: Build
    runs-on: windows-latest
    permissions:
      # write permission is required to create a github release
      contents: write
      # write permission is required for autolabeler
      # otherwise, read permission is required at least
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Corretto JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '11'
          cache: 'maven'

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots clean package -DskipTests

      - name: Upload Server Update
        uses: actions/upload-artifact@v2
        with:
          name: VPin-Studio-Server.zip
          path: |
            ${{ github.workspace }}/Output/VPin-Studio/VPin-Studio-Server.zip
          if-no-files-found: error

      - name: Draft Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: RELEASE_NOTES.md
          draft: true
          tag_name: 1.3.2
          # note you'll typically need to create a personal access token
          # with permissions to create releases in the other repo
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          files:
            ${{ github.workspace }}/Output/VPin-Studio/VPin-Studio-Client-Installer*.exe
            ${{ github.workspace }}/Output/VPin-Studio/VPin-Studio-Server.zip
        env:
          GITHUB_REPOSITORY: https://github.com/syd711/vpin-studio
